import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import "./common.scss";
import "./styles/roadmap.scss";
import "./styles/roadmapSlider.scss";
import "./styles/faq.scss";
import "./styles/footer.scss"

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const harngton = localFont({
  src: "./fonts/HARNGTON.woff",
  variable: "--font-harngton-sans",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${harngton.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
